### ISSUE TITLE
Consider simplifying sheet 08: Multilayer Perceptron

### ISSUE THREAD

**Issue by ahoereth** [CogSciUOS/MachineLearningSheets#1]
[Sheet 08](/CogSciUOS/ML2016/blob/469d990/sheet08/sheet08solutions.ipynb) is quite complex. Not only does it require extensive explanations, but additionally the sample solution is quite long and for Python beginners difficult to reason about because of advanced object orientation and class inheritance.

To simplify this I propose an approach more along the lines of my [naive MLP implementation](/ahoereth/nnplayground/blob/master/naiveMLP.ipynb). Specifically the first 4 cells:

* One can be (still) be guided from bottom to top, going from a single perceptron over a layer of perceptrons to a multilayer perceptron.
* Classes totally make sense for this. But inheritance is hard to reason about for beginners -- drop it.
* Drop having multiple different perceptrons. To allow this 
  * the input is provided as-is, as a list of values, one for each input neuron. 
  * Activation functions are not hard coded into the perceptrons implementation but passed to the constructor. This is also more similar to the behavior of common ANN frameworks.

The code is not ready to be deployed. If the general idea is approved I would open a PR changing a couple of things: 

* Replace `__call__` with `activate` or something simillar. While pretty, its confusing. For those coming from Java we should stick to something around "classes are called to create instances, instances provide methods".
* Maybe get rid of `__traverse__` because its very abstract. Redundant code here is not bad if its easier to understand.
* Consider getting rid of `zip` and similar shorthands. Some of those, again, are quite hard to reason about and duplicated/longer code is probably preferable.
* Adapt old exercises to new code.

Ping @krumnack @shoeffner @AndreaSuckro

**Comment by shoeffner** [comment]
I completely agree with those changes, especially since the MLP in Sheet 08 is not really learning anyway and we never managed to find the bug. Another very important reason is the length of the exercise.

Additionally we should also take a look into the custom approach and maybe even drop the solution there in favor of just one (working) solution.

**Comment by ahoereth** [comment]
Working on this on branch [SS17/sheet08](/CogSciUOS/ML2016/tree/SS17/sheet08) 

Difficulties:
- Implementation happens bottom up, from neuron to network
- Conceptualization generally is top down, from network to individual neuron

**Comment by ahoereth** [comment]
- [x] a50818c implements the circular example from TF playground -- this goes nicely with sheet 07. Is this desired?
- [x] The whole set of explanations (e.g. in 83c8f25) need more work. Maybe someone can help out on those.
- [ ] `adapt` in `MultilayerPerceptron` needs simplification. The loop over the tertiary (?) `zip` should probably be replaced with two individual loops -- maybe even without `zip`, although it simplifies the code greatly. Opinions?

**Comment by shoeffner** [comment]
> - a50818c implements the circular example from TF playground -- this goes nicely with sheet 07. Is this desired?

I think that would be nice to see, but it's not too important if it's too much work.

> - The whole set of explanations (e.g. in 83c8f25) need more work. Maybe someone can help out on those.

I can try, maybe we first add what you got and then create a new PR?

> - `adapt` in `MultilayerPerceptron` needs simplification. The loop over the tertiary (?) `zip` should probably be replaced with two individual loops -- maybe even without `zip`, although it simplifies the code greatly. Opinions?

It's tough, indeed - I don't have objections to make it easier. Especially concerning your comments about the difficulty and the zips

>     # TODO (ahoereth): Get rid of zip here because its 
>     #     difficult to grasp not only for python beginners.
> 
>     # TODO (ahoereth): The following line for many is hard and
>     #     therefore the need to remove the bias should be
>     #     somehow explained.```

I think it's more important to write code people can understand than to write code which seems more elegant in this case.

**Comment by ahoereth** [comment]
Closed by 1acac3a.
