### ISSUE TITLE
Tag SS16 course/branch out SS17 course/rename repo

### ISSUE THREAD

**Issue by ahoereth** [CogSciUOS/MachineLearningSheets#3]
- [x] Tag SS16 course
- [x] Master should represent SS17 from then on
- [x] Repo needs a more appropriate name
- [ ] Readme should make all this clear
- [ ] New tutors should be invited

**Comment by shoeffner** [comment]
> - [x] Tag SS16 course

Nice!

> - [ ] Master should represent SS17 from then on

Should we use orphaned branches per semester, i.e. rename `master` to `summer16` and just make `git checkout --orphan summer17` the default branch?

> - [ ] Repo needs a more appropriate name

`MachineLearning` vs `MachineLearningHomework` vs `MachineLearningSheets`, I am for the last.

> - [ ] Readme should make all this clear

Yes, I will then take care of that.

> - [ ] New tutors should be invited

This is the interesting point: I do not even know if they want to reuse it, they did not respond yet. Still we could prepare as if they were.

**Comment by ahoereth** [comment]
> Should we use orphaned branches per semester, i.e. rename master to summer16 and just make git checkout --orphan summer17 the default branch?

hugh? That's against the idea of git I would say. Most sheets will be reused, lets stick to master.

The other comments look good to me.
